name: Input Logger Test

on:
  workflow_dispatch:
    inputs:
      chatid:
        description: "Chat ID"
        required: true
      thread_id:
        description: "Thread ID (Optional)"
        required: false
      image:
        description: "Image to use"
        required: true
      bottoken:
        description: "Telegram Bot Token"
        required: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log Inputs
      run: |
        echo "### 📝 Logging Inputs ###"
        echo "Chat ID: ${{ github.event.inputs.chatid }}"
        echo "Thread ID: ${{ github.event.inputs.thread_id }}"
        echo "Image: ${{ github.event.inputs.image }}"
        echo "Bot Token: ${{ github.event.inputs.bottoken }}"

    - name: Log Environment Variables
      run: |
        echo "### 🌍 Environment Variables ###"
        echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
        echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"

    - name: Mask Sensitive Inputs
      run: |
        echo "::add-mask::${{ github.event.inputs.bottoken }}"
        echo "::add-mask::${{ github.event.inputs.chatid }}"

    - name: Test Thread ID Logic
      run: |
        THREAD_ID="${{ github.event.inputs.thread_id }}"
        
        if [[ -z "$THREAD_ID" || "$THREAD_ID" == "null" ]]; then
          echo "⚠️ THREAD_ID is empty or null!"
        else
          echo "✅ THREAD_ID is set: $THREAD_ID"
        fi
